### ISSUE TITLE
Add prettier code styling

### ISSUE THREAD

**Issue by CameronCT** [Keyma-sh/next#1]
We used to use prettier, but due to my negligence at wanting to configure it I ended up removing it over time and had it excluded on all of our builds.

Anyone who wants to take this on pls provide samples of what the config would look like

**Comment by Warrior-X** [comment]
Hi, I would like to work on this issue. Should I just make the config adhere to the current code style (always semis, single quotes, etc.)?

**Comment by CameronCT** [comment]
That would be preferred yes, I'm also not a person that likes more lines so a longer printWidth (I think that's what it is called) would be ideal.

**Comment by Warrior-X** [comment]
Would you prefer using `.editorconfig` (TOML), `.prettierrc` (JSON), or `.prettierrc` (YAML)?

**Comment by CameronCT** [comment]
`.prettierrc` (JSON) :)

**Comment by Warrior-X** [comment]
Sending a pr
