### ISSUE TITLE
Create bots when not enough people are in a match

### ISSUE THREAD

**Issue by Warrior-X** [Keyma-sh/next#111]
I'm not sure if this might be bad, but I recommend that if the amount of players in the match is less than say 3 there are a random number of bots (anywhere from 1-3) that spawn and take a random speed ranging from a little below the slowest player's average speed to a little bit above the second-slowest player's average speed (capped at a difference of about 10-15 wpm). They would take either a username of "Bot" or one of the auto-generated names that a guest gets. These are just example numbers, feel free to tweak them around a bit, it's just that I feel like having a match with one other person isn't really that fun.

**Comment by CameronCT** [comment]
We've considered doing this idea, however some players already dislike having one bot as is so adding another might not bold well for some of the community.

As for the strength of the bots, they may be nerfed at a later update.
