### ISSUE TITLE
Categorize quotes by length

### ISSUE THREAD

**Issue by Warrior-X** [Keyma-sh/next#115]
I think it would be beneficial to some people to be able to choose something like a “short quote” (like the feature in monkeytype). For example, if I’m learning a new keyboard layout, I probably won’t want to open a quote that’s like 50 words long and spend 5 minutes typing it (true story). This idea could also be used for words, again taking inspiration from monkeytype, where you can choose how many words you want (options are 25, 50, 100, 250).

**Comment by CameronCT** [comment]
If we introduced the ability to select quotes, we'd have to introduce the ability to select dictionary lengths. Which can skew pretty much all the leaderboards we have in place.

**Comment by CameronCT** [comment]
Not too sure what you mean - but okay.
