### ISSUE TITLE
/play/[mode] always redirect to /game/random

### ISSUE THREAD

**Issue by Veirt** [Keyma-sh/next#15]
**Describe the bug**

**To Reproduce**
1. Go to https://keyma.sh/play/dictionary
2. Redirected to ```/game/random```

**Expected behavior**
The route should redirect to```/game/dictionary```.

**Screenshots**
![bug](https://user-images.githubusercontent.com/55097092/145811275-547c68c9-e1b9-4498-bfd0-48c6d3584b06.gif)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 95.0

**Comment by Veirt** [comment]
I submitted a pull request in #16

**Comment by CameronCT** [comment]
Ty for this :)
