### ISSUE TITLE
Changing your username while looking at your profile will cause a 404 on save

### ISSUE THREAD

**Issue by Sellyme** [Keyma-sh/next#30]
**Steps to reproduce:**
1. Go to your profile by clicking your avatar in the top right of screen.
2. Click the Settings cog in the header.
3. Change your username and click "Save"

**Result:**
The page you're currently on refreshes, but as the URL for your profile is dependent on your username, it now 404s.

**Expected behaviour:**
The page will redirect to the new URL for your profile.

**Comment by CameronCT** [comment]
Does this problem still persist for you?

**Comment by Sellyme** [comment]
Yes.

**Comment by CameronCT** [comment]
Can you link me your profile.

**Comment by Sellyme** [comment]
https://keyma.sh/profile/Sellyme-0771/

**Comment by CameronCT** [comment]
Unable to reproduce, I change my username and it refreshes the page and still lets me access the profile. Can you possibly record a video?

**Comment by Sellyme** [comment]
https://user-images.githubusercontent.com/1928024/147652498-2b3fd5d3-b916-4947-928b-b6f7bafc8785.mp4

**Comment by CameronCT** [comment]
I see what you mean, not too sure if I'd label that a bug as your name no longer exists up until this point. Your new name is also not grabbed until after the refresh as your session JWT gets modified afterwards.
