### ISSUE TITLE
Ranked: Partial Text is retained in the following Round

### ISSUE THREAD

**Issue by HenryMorco** [Keyma-sh/next#38]
**Describe the bug**
When you lose to someone in Ranked, the screen automatically loads the next round.
But, any incorrect text you had typed in the last round is still retained.

This creates an unfair stumbling block for the loser of the match (they have to delete the bad text first)

**To Reproduce**
1. Participate in a Ranked Duel.
2. Make a mistake whilst opponent completes the round.
3. When the new round begins, text box still has the incorrect text left over from previous round.

**Expected behavior**
The text box should cleared every time a new round starts.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Edge
 - Version Version 96.0.1054.62

**Comment by CameronCT** [comment]
Can you send me a screenshot please?

**Comment by HenryMorco** [comment]
Sure, attached,

![image](https://user-images.githubusercontent.com/18065949/147858639-3fd71183-1a6d-4fd6-b34d-5755db9546a3.png)

**Comment by CameronCT** [comment]
Will be fixed in next update
