### ISSUE TITLE
Pressing Ctrl + W records a match in Activity Ladder

### ISSUE THREAD

**Issue by Killer8Hyper** [Keyma-sh/next#45]
**Describe the bug**
So while playing Activity Ladder I accidentaly pressed Ctrl + W and noticed that my 120 matches becomes 121.

**To Reproduce**
1. Competitions - Activity Ladder
2. Press Ctrl + W (I think it's the same as closing the tab)
3. Go back to the Activity Ladder Leaderboard to see the error

**Expected behavior**
I expected that it wouldn't freeze when pressing CTRL + W and do not record the match.

**Screenshots**
![image](https://user-images.githubusercontent.com/69343139/148891285-cf67a08c-ae0a-4e81-bea8-76d2ddcb3846.png)

I don't have a video for it because it always says, "Unable to find match, try again later." I don't understand why but yeah, I can't record.

**Desktop (please complete the following information):**
 - Windows
 - Chrome
 - 97.0.4692.71

**Comment by CameronCT** [comment]
This isn't a bug, I can't prevent a browser control functionality that is closing tabs or opening tabs. And if I could, I still wouldn't add a system that wouldn't make it register as a quit otherwise it would be subject to abuse.
