### ISSUE TITLE
I'm facing problem with finding match..

### ISSUE THREAD

**Issue by SoftEngine256** [Keyma-sh/next#49]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 
 - Browser Google Crome
 - Version  97.0.4692.71 (Official Build) (64-bit)
![keyma erroe](https://user-images.githubusercontent.com/86509804/149614855-0c0129f5-f275-4cac-939a-35ce2a5bb55b.jpg)

**Additional context**

**Comment by CameronCT** [comment]
Thank you for **not** following the instructions.

Like, is this a one time thing that happened. Is this consistently? Judging from your Locale in your task bar, are you from India? Is it possible that your latency is inconsistent when finding a match. I need more details, you have 12 hours until this is closed.
