### ISSUE TITLE
Screenshots of Quotes that have an Accuracy Issue

### ISSUE THREAD

**Issue by Killer8Hyper** [Keyma-sh/next#54]
![1_99%_Dec23](https://user-images.githubusercontent.com/69343139/151392155-6a6932dc-95dd-418b-bac6-cc96f941487b.png)
![2_99%_Dec23](https://user-images.githubusercontent.com/69343139/151392169-779ab0bd-0094-4098-bf42-a099f6f79193.png)
![3_99%_Jan5](https://user-images.githubusercontent.com/69343139/151392170-d44cd59e-2315-4997-92f4-ab3a7d7c5db1.png)
![4_99%_Jan5](https://user-images.githubusercontent.com/69343139/151392176-0de51cf8-a1c6-4b9a-8b05-f610f6ae71a2.png)
![5_99%_Jan8](https://user-images.githubusercontent.com/69343139/151392187-0bbfc5a9-8362-4214-89fc-8147ff114322.png)
![6_18th Place_Jan19](https://user-images.githubusercontent.com/69343139/151392194-2250f879-f1d0-4bf9-89b0-91c68671c2d4.png)
![7_98%_Jan24](https://user-images.githubusercontent.com/69343139/151392201-15b87f78-32cc-423f-86a4-8be01a748832.PNG)
![8_99%_Jan25](https://user-images.github
![9_99%_Jan](https://user-images.githubusercontent.com/69343139/151392227-c7c271d7-883d-4756-bb1f-7dc62c1af68c.PNG)
usercontent.com/69343139/151392212-343e65a0-61a8-4381-907f-b1baccc20c91.PNG)
![10_5th Place_Jan25](https://user-images.githubusercontent.com/69343139/151392242-8e83e7a0-c94c-4efe-8de4-cae4af468202.PNG)
![11_99%_Jan27](https://user-images.githubusercontent.com/69343139/151392262-fb3548c4-a1b5-4a29-88c1-58bd4b01b3ab.PNG)
![12_97%_Jan27 PNG](https://user-images.githubusercontent.com/69343139/151392609-835704e9-b096-4240-bfa2-a05928ef1a14.PNG)
![13_99%_Jan27](https://user-images.githubusercontent.com/69343139/151392618-6363792b-e33f-4a86-8e5e-e5158725b9e3.PNG)
![14_98%_Jan27](https://user-images.githubusercontent.com/69343139/151392622-fc150009-c11b-494c-9472-da27ee6bbb64.PNG)
![15_99%_Jan27](https://user-images.githubusercontent.com/69343139/151392624-0bbddf31-04c5-4a5c-ae6c-dab8e2d72c40.PNG)
![16_98%_Jan27](https://user-images.githubusercontent.com/69343139/151392628-65c73a0b-967a-4792-b602-e3d81dc63298.PNG)
![17_100%_0 Mistakes_Jan27](https://user-images.githubusercontent.com/69343139/151392629-6a783afd-bb32-422f-bd9b-5f67fa4f2bd7.PNG)
![18_99%_Jan27 PNG](https://user-images.githubusercontent.com/69343139/151392632-963bb86a-6e6b-4bca-ae4c-1a8f0709952d.PNG)
![19_98%_Jan27 PNG](https://user-images.githubusercontent.com/69343139/151392636-9d909b84-d8bd-458d-bf0a-91b3675fdd3b.PNG)
![20_99%_Jan27](https://user-images.githubusercontent.com/69343139/151392640-7b07c884-c379-49ff-8b78-e6f8bb178e60.PNG)
![21_76%_Jan27](https://user-images.githubusercontent.com/69343139/151392644-ffa12209-3701-4f18-ae24-76cf54beefcd.PNG)
![22_99%_Jan27](https://user-images.githubusercontent.com/69343139/151392649-e7250d29-08f6-405a-b184-51a71a840c8c.PNG)
![23_96%_Jan27](https://user-images.githubusercontent.com/69343139/151392651-83c22fb1-5e90-47e7-aa79-e8c67bc33c4c.PNG)

**Comment by Syndric** [comment]
Quote corrections should go in #text-bugs in the Keymash discord server in text format. Also, a lot of these don't seem to warrant a correction.

**Comment by CameronCT** [comment]
It's weird how this problem keeps coming back time and time again. Guess I'll have to take a look again :|

**Comment by CameronCT** [comment]
Fixed in v3.
