### ISSUE TITLE
Invalid Smooth Caret Speed Selected

### ISSUE THREAD

**Issue by MilkIsSC** [Keyma-sh/next#57]
**The Issue:**
Whenever I want to update my banner/border/playercards & acc info
It gives me an issue stating: Invalid smooth caret speed selected.

**Expected behavior**
All I want is the system to work correctly and let me update my **banner/border/playercards & acc info**

**Browser currently using:**
 - Browser [Brave]
 - Version [V1.35.101]

**Comment by Syndric** [comment]
Hey, can you try resetting your cache for Keymash? That's my biggest hunch. If that doesn't work, can you give a much more detailed explanation so it can be reproduced?

**Comment by MilkIsSC** [comment]
Hello there Syndric.
I tried resetting my cache for Keymash...But didn't really seem to work out.
I'm gonna send a video for my details: https://www.youtube.com/watch?v=FV7hkcIVxXA

Just for your information: I am not using any type of vpn to load the website.
Thanks for the support.

**Comment by Syndric** [comment]
Just making sure, did you actually select a caret speed under config?

**Comment by MilkIsSC** [comment]
I have Smooth caret (Beta) turned on | under config
But even if I try to disable it it gives me the error saying: Invalid Smooth Caret speed Selected

**Comment by CameronCT** [comment]
A while back we removed a specific Smooth Caret speed therefore this issue now occurs. All you have to do is select another smooth caret speed, as the error states.
