### ISSUE TITLE
Copying quotes difficult

### ISSUE THREAD

**Issue by Syndric** [Keyma-sh/next#64]
**Describe the bug**
Quotes cannot be copied by copying and pasting because there will be a newline after each word.

**To Reproduce**
1. Finish a match
2. Copy title, author, contributor, quote
3. Paste it in a text editor
4. There will be a newline after each word in the quote.

**Expected behavior**
Quotes should be able to be copied without the newline after each word.

**Additional context**
This can be fixed by pasting the quote into a generic search bar and then copying the search bar. All the newlines will be removed. Still hard to figure out.

![Screen Shot 2022-03-13 at 3 35 29 PM](https://user-images.githubusercontent.com/65517819/158076060-aedbd946-8ee9-426e-91d2-ec495a25cd92.png)
![Screen Shot 2022-03-13 at 3 37 04 PM](https://user-images.githubusercontent.com/65517819/158076072-631c71fc-5678-449a-90df-7b4f43bc00e3.png)

**Comment by CameronCT** [comment]
I'll add a copypasta link that copies the text content.
