### ISSUE TITLE
(1v1, BR) Rankings don't disappear after each match

### ISSUE THREAD

**Issue by Syndric** [Keyma-sh/next#65]
**Describe the bug**
The placement number/symbols on the side of a card do not go away after finishing a round in the player card format. (I do not know if this extends to list format.)

**To Reproduce**
1. Enter a BR or 1v1 match
2. Complete a quote
3. The symbol will not go away during the next round.

**Expected behavior**
The placement number/symbols should disappear and be replaced by each player's current word after the countdown for the next round ends.

**Screenshots**
(im referring to the symbol on the bottom right)
![Screen Shot 2022-03-14 at 4 23 49 PM](https://user-images.githubusercontent.com/65517819/158255050-ff4334b5-fdee-4e1f-9c2b-4e101d8ee855.png)

**Comment by CameronCT** [comment]
If using Racetrack or Leaderboard instead of the legacy playercard. Does this bug still persist?

**Comment by Syndric** [comment]
No

**Comment by CameronCT** [comment]
Okay, I'll take a look into it. The playercards will expire soon, but I'll fix it in the interim
