### ISSUE TITLE
Ranked Matchmaking bug

### ISSUE THREAD

**Issue by VFCTyrant** [Keyma-sh/next#86]
**Describe the bug**
Ranked queue leading to "Application error: a client-side exception has occurred (see the browser console for more informaation)
**To Reproduce**
1. Queue up for ranked from home page
2. Click on leaderboards
3. Wait for queue pop

**Expected behavior**
Get into ranked with no issues (what should happen)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera GX

**Additional context**
Not tested on other pages

**Comment by CameronCT** [comment]
fixed
