### ISSUE TITLE
Disable shortcuts in ranked

### ISSUE THREAD

**Issue by Syndric** [Keyma-sh/next#91]
**Describe the bug**
Not really a bug, but shortcuts should be disabled in ranked. This will prevent anyone pressing "new quote/dict/random" after completing a round (due to muscle memory). No confirmation is given to leave the page as of now, and in the future if a confirmation is given via browser dialogue, it usually results in a disconnect for the player.

**To Reproduce**
N/A

**Expected behavior**
I should not be able to accidentally leave a ranked match via keyboard shortcuts.

**Comment by CameronCT** [comment]
The exit dialogs are horrible and there's no way currently for me to not make it cancel the socket connection as of now. Unfortunately there's no fix, and realistically I should just remove the confirm dialog since it's not really useful anyways.

As for the bug with ranked, it'
